#!/bin/bash

conected=$(/opt/repository/dcm/dcm4che/bin/dcmsnd DCM4CHEE@localhost:11112 /storage/archive/2020/8/18/18/B6624232/EF71BAB8 | grep Connected | cut -d" " -f1)

echo $conected;


if [ $conected = "Connected" ]
then
        echo "no if"

else
        echo 'dcm com erro'
        ps aux | grep dcm | grep -v wlistdb | grep -v grep| grep -v S+ | awk '{print $2}' |{ while read linha2;
do
        echo $linha2;
        kill $linha2;
done
sleep 5
/etc/init.d/rundcm4chee start
}
fi

